//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcasaenk.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMapping {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMapping() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mcasaenk.Resources.ResourceMapping", typeof(ResourceMapping).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1;plains
        ///0;ocean
        ///1;plains
        ///2;desert
        ///3;stony_shore
        ///4;forest
        ///5;taiga
        ///6;swamp
        ///7;river
        ///8;nether
        ///9;the_end
        ///10;frozen_ocean
        ///11;frozen_river
        ///12;snowy_plains
        ///13;frozen_peaks
        ///14;mushroom_fields
        ///15;mushroom_fields
        ///16;beach
        ///17;desert
        ///18;forest
        ///19;taiga
        ///20;windswept_hills
        ///21;jungle
        ///22;jungle
        ///23;sparse_jungle
        ///24;deep_ocean
        ///25;stony_shore
        ///26;snowy_beach
        ///27;birch_forest
        ///28;birch_forest
        ///29;dark_forest
        ///30;snowy_taiga
        ///31;snowy_taiga
        ///32;old_growth_spruce_taiga
        ///33;old_growth_spruce_taiga
        ///34;s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string biome_names {
            get {
                return ResourceManager.GetString("biome_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minecraft:air;0
        ///minecraft:stone;707070
        ///minecraft:granite;976d4d
        ///minecraft:polished_granite;976d4d
        ///minecraft:diorite;fffcf5
        ///minecraft:polished_diorite;fffcf5
        ///minecraft:andesite;707070
        ///minecraft:polished_andesite;707070
        ///minecraft:grass_block;7fb238
        ///minecraft:dirt;976d4d
        ///minecraft:coarse_dirt;976d4d
        ///minecraft:podzol;815631
        ///minecraft:cobblestone;707070
        ///minecraft:oak_planks;8f7748
        ///minecraft:spruce_planks;815631
        ///minecraft:birch_planks;f7e9a3
        ///minecraft:jungle_planks;976d4d
        ///minecraft:acacia_planks; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string block_colors_map {
            get {
                return ResourceManager.GetString("block_colors_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --BIOMES--
        ///badlands;90814d;9e814d;3f76e4
        ///bamboo_jungle;59c93c;30bb0b;3f76e4
        ///basalt_deltas;bfb755;aea42a;3f76e4
        ///beach;91bd59;77ab2f;3f76e4
        ///birch_forest;88bb67;6ba941;3f76e4
        ///cherry_grove;b6db61;b6db61;5db7ef
        ///cold_ocean;8eb971;71a74d;3d57d6
        ///crimson_forest;bfb755;aea42a;3f76e4
        ///dark_forest;79c05a;59ae30;3f76e4
        ///deep_cold_ocean;8eb971;71a74d;3d57d6
        ///deep_dark;91bd59;77ab2f;3f76e4
        ///deep_frozen_ocean;8eb971;71a74d;3938c9
        ///deep_lukewarm_ocean;8eb971;71a74d;45adf2
        ///deep_ocean;8eb971;71a74d;3f76e4
        ///desert;bfb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string block_colors_mean {
            get {
                return ResourceManager.GetString("block_colors_mean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string shade3d_filter {
            get {
                return ResourceManager.GetString("shade3d_filter", resourceCulture);
            }
        }
    }
}
