//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcasaenk.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMapping {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMapping() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mcasaenk.Resources.ResourceMapping", typeof(ResourceMapping).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ___ {
            get {
                object obj = ResourceManager.GetObject("___", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the_void
        ///plains
        ///sunflower_plains
        ///snowy_plains
        ///ice_spikes
        ///desert
        ///swamp
        ///mangrove_swamp
        ///forest
        ///flower_forest
        ///birch_forest;
        ///dark_forest
        ///old_growth_birch_forest
        ///old_growth_pine_taiga
        ///old_growth_spruce_taiga
        ///taiga
        ///snowy_taiga
        ///savanna
        ///savanna_plateau
        ///windswept_hills
        ///windswept_gravelly_hills
        ///windswept_forest
        ///windswept_savanna
        ///jungle
        ///sparse_jungle
        ///bamboo_jungle
        ///badlands
        ///eroded_badlands
        ///wooded_badlands
        ///meadow
        ///cherry_grove
        ///grove
        ///snowy_slopes
        ///frozen_peaks
        ///jagged_peaks
        ///stony_peaks
        ///riv [rest of string was truncated]&quot;;.
        /// </summary>
        public static string biomes {
            get {
                return ResourceManager.GetString("biomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] capture {
            get {
                object obj = ResourceManager.GetObject("capture", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] colormap_bedrock {
            get {
                object obj = ResourceManager.GetObject("colormap_bedrock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] colormap_beta {
            get {
                object obj = ResourceManager.GetObject("colormap_beta", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] colormap_java {
            get {
                object obj = ResourceManager.GetObject("colormap_java", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] colormap_texture {
            get {
                object obj = ResourceManager.GetObject("colormap_texture", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] discard {
            get {
                object obj = ResourceManager.GetObject("discard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] end8 {
            get {
                object obj = ResourceManager.GetObject("end8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] grass {
            get {
                object obj = ResourceManager.GetObject("grass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] grass8 {
            get {
                object obj = ResourceManager.GetObject("grass8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon01 {
            get {
                object obj = ResourceManager.GetObject("icon01", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon2 {
            get {
                object obj = ResourceManager.GetObject("Icon2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string inherent_water_logged {
            get {
                return ResourceManager.GetString("inherent_water_logged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] nether8 {
            get {
                object obj = ResourceManager.GetObject("nether8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1;plains
        ///0;ocean
        ///1;plains
        ///2;desert
        ///3;stony_shore
        ///4;forest
        ///5;taiga
        ///6;swamp
        ///7;river
        ///8;nether_wastes
        ///9;the_end
        ///10;frozen_ocean
        ///11;frozen_river
        ///12;snowy_plains
        ///13;frozen_peaks
        ///14;mushroom_fields
        ///15;mushroom_fields
        ///16;beach
        ///17;desert
        ///18;forest
        ///19;taiga
        ///20;windswept_hills
        ///21;jungle
        ///22;jungle
        ///23;sparse_jungle
        ///24;deep_ocean
        ///25;stony_shore
        ///26;snowy_beach
        ///27;birch_forest
        ///28;birch_forest
        ///29;dark_forest
        ///30;snowy_taiga
        ///31;snowy_taiga
        ///32;old_growth_spruce_taiga
        ///33;old_growth_spruce_taig [rest of string was truncated]&quot;;.
        /// </summary>
        public static string oldbiomes {
            get {
                return ResourceManager.GetString("oldbiomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acacia_door;196;
        ///acacia_fence;192;0
        ///acacia_fence_gate;187;0,1,2,3,4,5,6,7
        ///acacia_leaves;161;0,4,8,12
        ///acacia_log;162;0,4,8,12
        ///acacia_planks;5;4
        ///acacia_sapling;6;4,12
        ///acacia_slab;126;4
        ///acacia_slab_top;126;12
        ///acacia_stairs;163;
        ///activator_rail;157;0,1,2,3,4,5,6,7,8,9,10,11,12,13
        ///air;0;0
        ///allium;38;2
        ///andesite;1;5
        ///anvil;145;0,1,2,3
        ///azure_bluet;38;3
        ///barrier;166;0
        ///beacon;138;0
        ///bed;26;0,1,2,3,8,9,10,11
        ///bedrock;7;0
        ///beetroots;207;0,1,2,3
        ///birch_door;194;
        ///birch_fence;189;0
        ///birch_fence_gate;184;0,1, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string oldblocks {
            get {
                return ResourceManager.GetString("oldblocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] question {
            get {
                object obj = ResourceManager.GetObject("question", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] rotate {
            get {
                object obj = ResourceManager.GetObject("rotate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] rotate2 {
            get {
                object obj = ResourceManager.GetObject("rotate2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allium
        ///attached_melon_stem
        ///attached_pumpkin_stem
        ///azure_bluet
        ///bamboo_sapling
        ///beacon
        ///beetroots
        ///bell
        ///black_candle
        ///black_stained_glass_pane
        ///blue_candle
        ///blue_orchid
        ///blue_stained_glass_pane
        ///brown_candle
        ///brown_mushroom
        ///brown_stained_glass_pane
        ///calibrated_sculk_sensor
        ///candle
        ///carrots
        ///chain
        ///cocoa
        ///cornflower
        ///crimson_fungus
        ///cyan_candle
        ///cyan_stained_glass_pane
        ///dandelion
        ///end_rod
        ///flower_pot
        ///glass
        ///glass_pane
        ///gray_candle
        ///gray_stained_glass_pane
        ///green_candle
        ///green_stained_glass_pane
        ///grindsto [rest of string was truncated]&quot;;.
        /// </summary>
        public static string shade3d_filter {
            get {
                return ResourceManager.GetString("shade3d_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grass;short_grass
        ///lily_pad;waterlily
        ///dirt_path;grass_path
        ///furnace;furnace_on
        ///melon_stem;attached_melon_stem
        ///oak_log;log
        ///portal;nether_portal
        ///pumpkin;carved_pumpkin
        ///pumpkin_stem;attached_pumpkin_stem
        ///redstone_lamp;redstone_lamp_off
        ///redstone_lamp;redstone_lamp_on
        ///redstone_torch;redstone_wall_torch
        ///redstone_torch;redstone_wall_torch
        ///stone;smooth_stone
        ///white_wool;wool.
        /// </summary>
        public static string synonymblocks {
            get {
                return ResourceManager.GetString("synonymblocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] unknown_pack {
            get {
                object obj = ResourceManager.GetObject("unknown_pack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] unknown_server {
            get {
                object obj = ResourceManager.GetObject("unknown_server", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // automatically generated by Utils.AssetsUtils.CreateVanillaDataAsset
        ///-- BIOMES --
        ///minecraft:badlands;2;0;4287660365;4288577869;4282349284;;
        ///minecraft:bamboo_jungle;0.95;0.9;0;0;4282349284;;
        ///minecraft:basalt_deltas;2;0;0;0;4282349284;;
        ///minecraft:beach;0.8;0.4;0;0;4282349284;;
        ///minecraft:birch_forest;0.6;0.6;0;0;4282349284;;
        ///minecraft:cherry_grove;0.5;0.8;4290173793;4290173793;4284332015;;
        ///minecraft:cold_ocean;0.5;0.5;0;0;4282210262;;
        ///minecraft:crimson_forest;2;0;0;0;4282349284;;
        ///minecraft:dark_for [rest of string was truncated]&quot;;.
        /// </summary>
        public static string vanilladatainfo {
            get {
                return ResourceManager.GetString("vanilladatainfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- BIOMES --
        ///minecraft:badlands;2;0;4287660365;4288577869;4282349284;;
        ///minecraft:bamboo_jungle;0.95;0.9;0;0;4282349284;;
        ///minecraft:basalt_deltas;2;0;0;0;4282349284;;
        ///minecraft:beach;0.8;0.4;0;0;4282349284;;
        ///minecraft:birch_forest;0.6;0.6;0;0;4282349284;;
        ///minecraft:cherry_grove;0.5;0.8;4290173793;4290173793;4284332015;;
        ///minecraft:cold_ocean;0.5;0.5;0;0;4282210262;;
        ///minecraft:crimson_forest;2;0;0;0;4282349284;;
        ///minecraft:dark_forest;0.7;0.8;0;0;4282349284;dark_forest;
        ///minecraft:deep_cold_ocean;0.5;0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string vanilladatainfo117 {
            get {
                return ResourceManager.GetString("vanilladatainfo117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] wrench {
            get {
                object obj = ResourceManager.GetObject("wrench", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
