//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcasaenk.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMapping {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMapping() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mcasaenk.Resources.ResourceMapping", typeof(ResourceMapping).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid;-1
        ///ocean;0
        ///plains;1
        ///desert;2
        ///mountains;3
        ///forest;4
        ///taiga;5
        ///swamp;6
        ///river;7
        ///nether;8
        ///nether_wastes;8
        ///the_end;9
        ///frozen_ocean;10
        ///frozen_river;11
        ///snowy_tundra;12
        ///snowy_mountains;13
        ///mushroom_fields;14
        ///mushroom_field_shore;15
        ///beach;16
        ///desert_hills;17
        ///wooded_hills;18
        ///taiga_hills;19
        ///mountain_edge;20
        ///jungle;21
        ///jungle_hills;22
        ///jungle_edge;23
        ///deep_ocean;24
        ///stone_shore;25
        ///snowy_beach;26
        ///birch_forest;27
        ///birch_forest_hills;28
        ///dark_forest;29
        ///snowy_taiga;30
        ///snowy_taiga_hills;31
        ///gian [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string biome_names {
            get {
                return ResourceManager.GetString("biome_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minecraft:air;0
        ///minecraft:stone;707070
        ///minecraft:granite;976d4d
        ///minecraft:polished_granite;976d4d
        ///minecraft:diorite;fffcf5
        ///minecraft:polished_diorite;fffcf5
        ///minecraft:andesite;707070
        ///minecraft:polished_andesite;707070
        ///minecraft:grass_block;7fb238
        ///minecraft:dirt;976d4d
        ///minecraft:coarse_dirt;976d4d
        ///minecraft:podzol;815631
        ///minecraft:cobblestone;707070
        ///minecraft:oak_planks;8f7748
        ///minecraft:spruce_planks;815631
        ///minecraft:birch_planks;f7e9a3
        ///minecraft:jungle_planks;976d4d
        ///minecraft:acacia_planks; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string block_colors_map {
            get {
                return ResourceManager.GetString("block_colors_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to badlands;90814d;9e814d;3f76e4
        ///bamboo_jungle;59c93c;30bb0b;3f76e4
        ///basalt_deltas;bfb755;aea42a;3f76e4
        ///beach;91bd59;77ab2f;3f76e4
        ///birch_forest;88bb67;6ba941;3f76e4
        ///cherry_grove;b6db61;b6db61;5db7ef
        ///cold_ocean;8eb971;71a74d;3d57d6
        ///crimson_forest;bfb755;aea42a;3f76e4
        ///dark_forest;79c05a;59ae30;3f76e4
        ///deep_cold_ocean;8eb971;71a74d;3d57d6
        ///deep_dark;91bd59;77ab2f;3f76e4
        ///deep_frozen_ocean;8eb971;71a74d;3938c9
        ///deep_lukewarm_ocean;8eb971;71a74d;45adf2
        ///deep_ocean;8eb971;71a74d;3f76e4
        ///desert;bfb755;aea42a;3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string block_colors_mean {
            get {
                return ResourceManager.GetString("block_colors_mean", resourceCulture);
            }
        }
    }
}
