//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utils.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the_void;0
        ///plains;1
        ///sunflower_plains;2
        ///snowy_plains;3
        ///ice_spikes;4
        ///desert;5
        ///swamp;6
        ///mangrove_swamp;7
        ///forest;8
        ///flower_forest;9
        ///birch_forest;10
        ///dark_forest;11
        ///old_growth_birch_forest;12
        ///old_growth_pine_taiga;13
        ///old_growth_spruce_taiga;14
        ///taiga;15
        ///snowy_taiga;16
        ///savanna;17
        ///savanna_plateau;18
        ///windswept_hills;19
        ///windswept_gravelly_hills;20
        ///windswept_forest;21
        ///windswept_savanna;22
        ///jungle;23
        ///sparse_jungle;24
        ///bamboo_jungle;25
        ///badlands;26
        ///eroded_badlands;27
        ///wooded_badlands;28
        ///meadow;29
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string javabiomes {
            get {
                return ResourceManager.GetString("javabiomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --TINT--
        ///j,b;grass_block;grass
        ///j,b;short_grass;grass
        ///j,b;tall_grass;grass
        ///j,b;large_fern;grass
        ///j,b;fern;grass
        ///j,b;sugar_cane;grass
        ///j,b;oak_leaves;foliage
        ///j,b;jungle_leaves;foliage
        ///j,b;acacia_leaves;foliage
        ///j,b;dark_oak_leaves;foliage
        ///j,b;mangrove_leaves;foliage
        ///j,b;vine;foliage
        ///j,b;water;water
        ///--TINT--
        ///
        ///--JAVACANTINT--
        ///birch_leaves;foliage;(#80A755)
        ///spruce_leaves;foliage;(#619961)
        ///lily_pad;grass;(#208030)
        ///melon_stem;grass;(#E0C71C)
        ///attached_melon_stem;grass;(#E0C71C)
        ///pumpkin_stem;grass [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tintblocks {
            get {
                return ResourceManager.GetString("tintblocks", resourceCulture);
            }
        }
    }
}
